esphome:
  name: lbe_camera

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""
wifi:
  ssid: "FabLab-IoT"
  password: "FabLab@#J500_IoT"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lbe Camera Fallback Hotspot"
    password: "AcQhVs9LLKZu"


web_server:
  port: 80

captive_portal:

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  vertical_flip: False
  horizontal_mirror: False


  # Image settings
  name: ESP CAM
  resolution: 800X600
  

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 5s
  - platform: uptime
    name: Uptime Sensor


esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

  # ...
# Flashlight
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4

## GPIO_4 is the flash light pin
light:
  - platform: binary
    output: gpio_4
    name: flashlight